// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmWpPSNDoF7-UFacGNAX41ft8UxdU3wDE',
    appId: '1:712290583140:web:fc3171244df95c27381571',
    messagingSenderId: '712290583140',
    projectId: 'notes-ba0a5',
    authDomain: 'notes-ba0a5.firebaseapp.com',
    storageBucket: 'notes-ba0a5.firebasestorage.app',
    measurementId: 'G-SC92PLBB1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW7ypuekis4SNppmvHuVvNGaayRIXu54o',
    appId: '1:712290583140:android:69b468382f3de3e0381571',
    messagingSenderId: '712290583140',
    projectId: 'notes-ba0a5',
    storageBucket: 'notes-ba0a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnyyUDmPyggW9xP1B8JztxMcHt0MHdwlg',
    appId: '1:712290583140:ios:5fc495b51114ce2d381571',
    messagingSenderId: '712290583140',
    projectId: 'notes-ba0a5',
    storageBucket: 'notes-ba0a5.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnyyUDmPyggW9xP1B8JztxMcHt0MHdwlg',
    appId: '1:712290583140:ios:5fc495b51114ce2d381571',
    messagingSenderId: '712290583140',
    projectId: 'notes-ba0a5',
    storageBucket: 'notes-ba0a5.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmWpPSNDoF7-UFacGNAX41ft8UxdU3wDE',
    appId: '1:712290583140:web:c7ecb844e8e2ea40381571',
    messagingSenderId: '712290583140',
    projectId: 'notes-ba0a5',
    authDomain: 'notes-ba0a5.firebaseapp.com',
    storageBucket: 'notes-ba0a5.firebasestorage.app',
    measurementId: 'G-0MCKG3HDLM',
  );
}
